### ISSUE TITLE
How to find cookie?

### ISSUE THREAD

**Issue by KZavi** [610yilingliu/missevan_download#3]
I do not know which one to use, please help.

**Comment by 610yilingliu** [comment]
> I do not know which one to use, please help.

Open your google chrome - more tools -developer tool - network
login misseven and open a payed audio, then you can find your cookie here:
![image](https://user-images.githubusercontent.com/41269216/187140582-fcac584d-92e2-4349-9a23-2c6c3b92d374.png)
